services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    develop:
      watch:
        - action: sync
          path: .
          target: /application
    volumes:
      - ./data/test.db:/data/test.db
    env_file:
      - .env
    environment:
      - DB_PATH=/data/test.db
